# Generated by Django 4.2.27 on 2026-01-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0002_add_counter_quota_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("counters", "Counters & Quotas"),
                    ("api_keys", "API Keys"),
                    ("database", "Database"),
                    ("cache", "Cache"),
                    ("external", "External Services"),
                    ("game_servers", "Game Servers"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
