# Generated by Django 4.2.27 on 2025-12-30 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("can_raid", models.BooleanField(default=False)),
                ("raid_note", models.CharField(blank=True, max_length=200)),
                ("can_steal", models.BooleanField(default=False)),
                ("steal_note", models.CharField(blank=True, max_length=200)),
                ("can_mug", models.BooleanField(default=False)),
                ("mug_note", models.CharField(blank=True, max_length=200)),
                ("can_kidnap", models.BooleanField(default=False)),
                ("kidnap_note", models.CharField(blank=True, max_length=200)),
                ("can_base", models.BooleanField(default=False)),
                ("base_note", models.CharField(blank=True, max_length=200)),
                ("can_have_printers", models.BooleanField(default=False)),
                ("printers_note", models.CharField(blank=True, max_length=200)),
                ("additional_notes", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "order", "job_name"],
            },
        ),
        migrations.CreateModel(
            name="RuleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Rule Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="rules.rulecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "code"],
                "unique_together": {("category", "code")},
            },
        ),
    ]
