# Generated by Django 4.2.27 on 2025-12-31 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SteamProfileSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steam_id_64", models.CharField(db_index=True, max_length=50)),
                ("steam_id", models.CharField(blank=True, max_length=50)),
                ("search_count", models.IntegerField(default=1)),
                ("first_searched_at", models.DateTimeField(auto_now_add=True)),
                ("last_searched_at", models.DateTimeField(auto_now=True)),
                ("persona_name", models.CharField(blank=True, max_length=255)),
                ("profile_url", models.URLField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("profile_state", models.CharField(blank=True, max_length=20)),
                ("real_name", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("account_created", models.DateTimeField(blank=True, null=True)),
                ("vac_bans", models.IntegerField(default=0)),
                ("game_bans", models.IntegerField(default=0)),
                ("days_since_last_ban", models.IntegerField(blank=True, null=True)),
                ("community_banned", models.BooleanField(default=False)),
                ("trade_ban", models.CharField(blank=True, max_length=50)),
                ("is_private", models.BooleanField(default=False)),
                ("is_limited", models.BooleanField(default=False)),
                ("level", models.IntegerField(blank=True, null=True)),
                (
                    "last_searched_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="steam_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Steam Profile Search",
                "verbose_name_plural": "Steam Profile Searches",
                "ordering": ["-last_searched_at"],
            },
        ),
        migrations.CreateModel(
            name="SteamProfileHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
                ("persona_name", models.CharField(blank=True, max_length=255)),
                ("avatar_url", models.URLField(blank=True)),
                ("profile_state", models.CharField(blank=True, max_length=20)),
                ("vac_bans", models.IntegerField(default=0)),
                ("game_bans", models.IntegerField(default=0)),
                ("days_since_last_ban", models.IntegerField(blank=True, null=True)),
                ("changes_detected", models.JSONField(blank=True, default=dict)),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="templates_manager.steamprofilesearch",
                    ),
                ),
                (
                    "searched_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Steam Profile History",
                "verbose_name_plural": "Steam Profile Histories",
                "ordering": ["-searched_at"],
            },
        ),
        migrations.AddField(
            model_name="refundtemplate",
            name="steam_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_templates",
                to="templates_manager.steamprofilesearch",
            ),
        ),
    ]
