# Generated by Django 4.2.27 on 2025-12-31 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates_manager", "0002_steamprofilesearch_steamprofilehistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffApplicationResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=100)),
                ("steam_id_64", models.CharField(blank=True, max_length=50)),
                ("discord_username", models.CharField(blank=True, max_length=100)),
                ("positive_rep", models.TextField(verbose_name="+ Rep")),
                ("neutral_rep", models.TextField(blank=True, verbose_name="+/- Rep")),
                ("negative_rep", models.TextField(blank=True, verbose_name="- Rep")),
                ("overall_comment", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1/5"),
                            (2, "2/5"),
                            (3, "3/5"),
                            (4, "4/5"),
                            (5, "5/5"),
                        ],
                        default=3,
                    ),
                ),
                ("recommend_hire", models.BooleanField(default=False)),
                ("recommended_role", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "steam_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_applications",
                        to="templates_manager.steamprofilesearch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Application Response",
                "verbose_name_plural": "Staff Application Responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_ign",
                    models.CharField(
                        max_length=100, verbose_name="Reported Player IGN"
                    ),
                ),
                ("steam_id", models.CharField(max_length=50)),
                ("steam_id_64", models.CharField(blank=True, max_length=50)),
                (
                    "case_link",
                    models.URLField(verbose_name="Discord Case Transcript Link"),
                ),
                ("report_reason", models.TextField()),
                ("evidence_provided", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_reason", models.TextField()),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("none", "No Action"),
                            ("warned", "Warned"),
                            ("banned", "Banned"),
                            ("kicked", "Kicked"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "steam_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_reports",
                        to="templates_manager.steamprofilesearch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Report",
                "verbose_name_plural": "Player Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BanExtensionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_ign",
                    models.CharField(max_length=100, verbose_name="In-Game Name"),
                ),
                ("steam_id", models.CharField(max_length=50)),
                ("steam_id_64", models.CharField(blank=True, max_length=50)),
                ("server_number", models.CharField(max_length=10)),
                ("ban_reason", models.TextField()),
                ("current_ban_time", models.CharField(max_length=100)),
                ("required_ban_time", models.CharField(max_length=100)),
                ("extension_reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ban_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ban_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "steam_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ban_extensions",
                        to="templates_manager.steamprofilesearch",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ban Extension",
                "verbose_name_plural": "Ban Extensions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("refund", "Refund"),
                            ("ban_extension", "Ban Extension"),
                            ("player_report", "Player Report"),
                            ("staff_application", "Staff Application"),
                        ],
                        max_length=20,
                    ),
                ),
                ("template_id", models.IntegerField()),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Comment",
                "verbose_name_plural": "Template Comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "template_id"],
                        name="templates_m_templat_bfb864_idx",
                    )
                ],
            },
        ),
    ]
