# Generated by Django 4.2.27 on 2025-12-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "templates_manager",
            "0003_staffapplicationresponse_playerreporttemplate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="steamprofilesearch",
            name="city_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="comment_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="country_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="custom_url",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Custom URL"
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="game_extra_info",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="game_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="game_server_ip",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="last_logoff",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="persona_state",
            field=models.IntegerField(default=0, verbose_name="Persona State"),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="persona_state_flags",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="state_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="steam_id_3",
            field=models.CharField(blank=True, max_length=50, verbose_name="SteamID3"),
        ),
    ]
