# Generated by Django 4.2.27 on 2025-12-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_manager", "0004_steamprofilesearch_city_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="steamprofilesearch",
            name="account_id",
            field=models.CharField(
                blank=True, help_text="Steam Account ID", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="estimated_value",
            field=models.CharField(
                blank=True, help_text="Estimated account value", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="fivem_hex",
            field=models.CharField(
                blank=True, help_text="FiveM HEX identifier", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="invite_url",
            field=models.URLField(blank=True, help_text="Steam invite URL"),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="invite_url_short",
            field=models.URLField(blank=True, help_text="Short Steam invite URL"),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="last_scraped_at",
            field=models.DateTimeField(
                blank=True, help_text="When profile was last scraped", null=True
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="online_status",
            field=models.CharField(
                blank=True, help_text="Current online status", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="rating_count",
            field=models.IntegerField(
                blank=True, help_text="Number of ratings", null=True
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="rating_value",
            field=models.FloatField(
                blank=True, help_text="Community rating value", null=True
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="scrape_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw scraped data"
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="scraped_description",
            field=models.TextField(
                blank=True, help_text="Profile description from scraper"
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="steam_id_2",
            field=models.CharField(
                blank=True, help_text="Steam2 ID format", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="steamprofilesearch",
            name="vanity_url",
            field=models.CharField(
                blank=True, help_text="Custom vanity URL", max_length=255
            ),
        ),
    ]
