# Generated by Django 4.2.27 on 2025-12-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_manager", "0005_steamprofilesearch_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="steamprofilesearch",
            name="account_name",
            field=models.CharField(
                blank=True,
                help_text="Steam account login name (from steamid.io)",
                max_length=255,
            ),
        ),
    ]
