# Generated by Django 4.2.27 on 2025-12-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_manager", "0006_steamprofilesearch_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="steamprofilesearch",
            name="past_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of past display names with timestamps",
            ),
        ),
    ]
