# Generated by Django 4.2.27 on 2025-12-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_manager", "0007_steamprofilesearch_past_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="steamprofilesearch",
            name="vac_ban_dates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of VAC ban dates from steamid.pro",
            ),
        ),
    ]
