# Generated by Django 4.2.27 on 2025-12-31 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates_manager", "0008_steamprofilesearch_vac_ban_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="SteamProfileNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General Note"),
                            ("warning_verbal", "Verbal Warning"),
                            ("warning_written", "Written Warning"),
                            ("ban_history", "Ban History"),
                            ("behavior", "Behavior Note"),
                            ("investigation", "Under Investigation"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="For warnings, marks if still active"
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=1,
                        help_text="Severity level of the note/warning",
                    ),
                ),
                (
                    "server",
                    models.CharField(
                        blank=True,
                        help_text="Server where incident occurred",
                        max_length=50,
                    ),
                ),
                (
                    "incident_date",
                    models.DateTimeField(
                        blank=True, help_text="When the incident occurred", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steam_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_steam_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "steam_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="templates_manager.steamprofilesearch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Steam Profile Note",
                "verbose_name_plural": "Steam Profile Notes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["steam_profile", "note_type"],
                        name="templates_m_steam_p_bc0bc1_idx",
                    ),
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="templates_m_is_acti_329c21_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SteamProfileBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of tags like ["suspicious", "frequent player"]',
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Pin this bookmark to the top"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "steam_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="templates_manager.steamprofilesearch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steam_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Steam Profile Bookmark",
                "verbose_name_plural": "Steam Profile Bookmarks",
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_pinned"],
                        name="templates_m_user_id_be0d53_idx",
                    )
                ],
                "unique_together": {("user", "steam_profile")},
            },
        ),
    ]
