# Generated by Django 4.2.27 on 2025-12-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_manager", "0009_steamprofilenote_steamprofilebookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steamprofilenote",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("general", "General Note"),
                    ("warning_verbal", "Verbal Warning"),
                    ("behavior", "Behavior Note"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
