# Generated by Django 4.2.27 on 2025-12-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_manager", "0010_alter_steamprofilenote_note_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="steamprofilenote",
            name="incident_date",
        ),
        migrations.AddField(
            model_name="steamprofilenote",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When the note expires", null=True
            ),
        ),
    ]
