# Generated by Django 4.2.27 on 2025-12-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_manager", "0011_remove_steamprofilenote_incident_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundtemplate",
            name="server",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
