# Generated by Django 4.2.27 on 2025-12-30 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                ("records_synced", models.IntegerField(default=0)),
                ("records_added", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_removed", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-synced_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(max_length=50)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("active_time", models.CharField(blank=True, max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("steam_id", models.CharField(blank=True, max_length=50, null=True)),
                ("discord_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "discord_tag",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_roster",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Roster",
                "ordering": ["rank", "name"],
            },
        ),
    ]
