# Generated by Django 4.2.27 on 2025-12-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffroster",
            options={
                "ordering": ["rank_priority", "name"],
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Roster",
            },
        ),
        migrations.AddField(
            model_name="staffroster",
            name="rank_priority",
            field=models.IntegerField(default=999),
        ),
    ]
