# Generated by Django 4.2.27 on 2025-12-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staffroster_options_staffroster_rank_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffroster",
            name="discord_activity",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="staffroster",
            name="discord_custom_status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="staffroster",
            name="discord_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("idle", "Idle"),
                    ("dnd", "Do Not Disturb"),
                    ("offline", "Offline"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staffroster",
            name="discord_status_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
