# Generated by Django 4.2.27 on 2025-12-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_add_discord_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffroster",
            name="is_active_in_app",
            field=models.BooleanField(default=False, verbose_name="Active in App"),
        ),
        migrations.AddField(
            model_name="staffroster",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Seen"),
        ),
    ]
