# Generated by Django 4.2.27 on 2025-12-31 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
        ("staff", "0004_add_activity_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerSessionAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("all_time", "All Time"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period Start")),
                (
                    "period_end",
                    models.DateField(blank=True, null=True, verbose_name="Period End"),
                ),
                (
                    "total_time",
                    models.IntegerField(default=0, verbose_name="Total Time (seconds)"),
                ),
                (
                    "session_count",
                    models.IntegerField(default=0, verbose_name="Session Count"),
                ),
                (
                    "avg_session_time",
                    models.IntegerField(
                        default=0, verbose_name="Average Session Time (seconds)"
                    ),
                ),
                (
                    "longest_session",
                    models.IntegerField(
                        default=0, verbose_name="Longest Session (seconds)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_aggregates",
                        to="servers.gameserver",
                        verbose_name="Server",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_aggregates",
                        to="staff.staffroster",
                        verbose_name="Staff Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Aggregate",
                "verbose_name_plural": "Session Aggregates",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["staff", "period_type", "period_start"],
                        name="staff_serve_staff_i_eeb4fb_idx",
                    ),
                    models.Index(
                        fields=["server", "period_type", "period_start"],
                        name="staff_serve_server__5bff69_idx",
                    ),
                ],
                "unique_together": {("staff", "server", "period_type", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="ServerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_time", models.DateTimeField(verbose_name="Join Time")),
                (
                    "leave_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Leave Time"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="Duration (seconds)"),
                ),
                ("steam_id", models.CharField(blank=True, max_length=50, null=True)),
                ("player_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_sessions",
                        to="servers.gameserver",
                        verbose_name="Server",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_sessions",
                        to="staff.staffroster",
                        verbose_name="Staff Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Server Session",
                "verbose_name_plural": "Server Sessions",
                "ordering": ["-join_time"],
                "indexes": [
                    models.Index(
                        fields=["staff", "join_time"],
                        name="staff_serve_staff_i_ade07a_idx",
                    ),
                    models.Index(
                        fields=["server", "join_time"],
                        name="staff_serve_server__0c1b1e_idx",
                    ),
                    models.Index(
                        fields=["steam_id", "join_time"],
                        name="staff_serve_steam_i_0b498e_idx",
                    ),
                ],
            },
        ),
    ]
