# Generated by Django 4.2.27 on 2025-12-31 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0005_serversessionaggregate_serversession"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffHistoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("joined", "Joined Staff"),
                            ("promoted", "Promoted"),
                            ("demoted", "Demoted"),
                            ("role_change", "Role Changed"),
                            ("left", "Left Staff"),
                            ("removed", "Removed"),
                            ("rejoined", "Rejoined Staff"),
                        ],
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "old_rank",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Old Rank"
                    ),
                ),
                (
                    "new_rank",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="New Rank"
                    ),
                ),
                (
                    "old_rank_priority",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Old Rank Priority"
                    ),
                ),
                (
                    "new_rank_priority",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="New Rank Priority"
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Event Date")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "auto_detected",
                    models.BooleanField(default=True, verbose_name="Auto Detected"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_events_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_events",
                        to="staff.staffroster",
                        verbose_name="Staff Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff History Event",
                "verbose_name_plural": "Staff History Events",
                "ordering": ["-event_date"],
                "indexes": [
                    models.Index(
                        fields=["staff", "event_date"],
                        name="staff_staff_staff_i_68974c_idx",
                    ),
                    models.Index(
                        fields=["event_type", "event_date"],
                        name="staff_staff_event_t_a9f50e_idx",
                    ),
                ],
            },
        ),
    ]
