# Generated by Django 4.2.27 on 2026-01-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_refactor_staff_roster"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffroster",
            options={
                "ordering": ["rank_priority", "staff__name"],
                "verbose_name": "Roster Entry",
                "verbose_name_plural": "Staff Roster",
            },
        ),
        migrations.AlterField(
            model_name="serversession",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_sessions",
                to="staff.staff",
                verbose_name="Staff Member",
            ),
        ),
        migrations.AlterField(
            model_name="serversessionaggregate",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_aggregates",
                to="staff.staff",
                verbose_name="Staff Member",
            ),
        ),
        migrations.AlterField(
            model_name="staffhistoryevent",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_events",
                to="staff.staff",
                verbose_name="Staff Member",
            ),
        ),
        migrations.AlterField(
            model_name="staffroster",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roster_entries",
                to="staff.staff",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffroster",
            unique_together={("staff", "is_active")},
        ),
    ]
