# Generated by Django 4.2.27 on 2026-01-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0010_alter_staffroster_options_alter_serversession_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="steam_name",
            field=models.CharField(
                blank=True,
                help_text="Current Steam persona name, synced periodically from Steam API",
                max_length=100,
                null=True,
                verbose_name="Steam Display Name",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="steam_name_last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Steam name was last fetched from Steam API",
                null=True,
                verbose_name="Steam Name Last Updated",
            ),
        ),
    ]
