# Generated by Django 4.2.27 on 2025-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_legacy_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
