# Generated by Django 4.2.27 on 2026-01-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_legacy_staff_user_staff_left_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="use_24_hour_time",
            field=models.BooleanField(
                default=True,
                help_text="Display times in 24-hour format instead of 12-hour AM/PM",
                verbose_name="Use 24-hour time format",
            ),
        ),
    ]
