# Generated by Django 4.2.27 on 2026-01-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_use_24_hour_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="setup_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed the initial setup wizard",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="setup_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when setup wizard was completed",
                null=True,
            ),
        ),
    ]
