# Generated by Django 4.2.27 on 2025-12-30 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("server_name", models.CharField(blank=True, max_length=200)),
                ("map_name", models.CharField(blank=True, max_length=100)),
                ("max_players", models.IntegerField(default=0)),
                ("current_players", models.IntegerField(default=0)),
                ("last_query", models.DateTimeField(blank=True, null=True)),
                ("last_successful_query", models.DateTimeField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "unique_together": {("ip_address", "port")},
            },
        ),
        migrations.CreateModel(
            name="ServerPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
                ("duration", models.IntegerField(default=0)),
                ("steam_id", models.CharField(blank=True, max_length=50, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("staff_rank", models.CharField(blank=True, max_length=50)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="servers.gameserver",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServerStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("player_count", models.IntegerField()),
                ("staff_count", models.IntegerField(default=0)),
                ("is_online", models.BooleanField()),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="servers.gameserver",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["server", "timestamp"],
                        name="servers_ser_server__6ee9ad_idx",
                    )
                ],
            },
        ),
    ]
