# Generated by Django 4.2.27 on 2025-12-30 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counter_type", models.CharField(max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("increment", "Increment"),
                            ("decrement", "Decrement"),
                            ("set", "Set Value"),
                            ("reset", "Reset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.IntegerField()),
                ("new_value", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counter_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Counter History",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CounterSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sit_count", models.IntegerField(default=0)),
                ("ticket_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counter_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counter_type",
                    models.CharField(
                        choices=[("sit", "Sit"), ("ticket", "Ticket")], max_length=20
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_type", models.CharField(default="total", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {
                    ("user", "counter_type", "period_type", "period_start")
                },
            },
        ),
    ]
