# Generated by Django 4.2.27 on 2026-01-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0002_sit_recording_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="counter",
            name="weekly_reset_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
